// Static rule tables used by the 5e editor engine.

export const SPELL_LEVEL_LABELS = ["Truque", "1º círculo", "2º círculo", "3º círculo", "4º círculo", "5º círculo", "6º círculo", "7º círculo", "8º círculo", "9º círculo"];
export const MAGIC_SPELL_TAG_FILTERS = [
  { value: "all", label: "Todas" },
  { value: "selected", label: "Selecionadas" },
  { value: "ritual", label: "Ritual" },
  { value: "concentracao", label: "Concentração" },
  { value: "dano", label: "Dano" },
  { value: "cura", label: "Cura" },
  { value: "defesa", label: "Defesa" },
  { value: "controle", label: "Controle" },
  { value: "utilidade", label: "Utilidade" },
];
export const MAGIC_FILTER_DEFAULTS = {
  query: "",
  level: "all",
  school: "all",
  tag: "all",
};
export const STANDARD_ABILITY_SET = [15, 14, 13, 12, 10, 8];
export const POINT_BUY_COSTS = {
  8: 0,
  9: 1,
  10: 2,
  11: 3,
  12: 4,
  13: 5,
  14: 7,
  15: 9,
};
export const DISTANCE_UNITS = {
  ft: { label: "ft", factorToMeters: 0.3048, decimals: 0 },
  m: { label: "m", factorToMeters: 1, decimals: 0 },
};
export const WEIGHT_UNITS = {
  lb: { label: "lb", factorToKg: 0.45359237, decimals: 0 },
  kg: { label: "kg", factorToKg: 1, decimals: 1 },
};
export const DAMAGE_TYPE_LABELS = {
  concussao: "concussão",
  cortante: "cortante",
  perfurante: "perfurante",
  acido: "ácido",
  eletrico: "elétrico",
  fogo: "fogo",
  frio: "frio",
  forca: "força",
  necrotico: "necrótico",
  psiquico: "psíquico",
  radiante: "radiante",
  trovejante: "trovejante",
  veneno: "veneno",
};
export const PROFICIENCY_LABEL_OVERRIDES = {
  leve: "armaduras leves",
  media: "armaduras médias",
  pesada: "armaduras pesadas",
  escudo: "escudos",
  simples: "armas simples",
  marcial: "armas marciais",
  "instrumentos-musicais": "instrumentos musicais",
  "ferramentas-de-ladrao": "ferramentas de ladrão",
  "ferramentas-de-falsificacao": "ferramentas de falsificação",
  "ferramentas-de-navegacao": "ferramentas de navegação",
  "ferramentas-de-artesao": "ferramentas de artesão",
  "ferramentas-de-artesao-um": "um tipo de ferramentas de artesão",
  "jogo-de-cartas": "baralho",
  "jogo-de-dados": "dados",
};
export const FIGHTING_STYLE_DEFINITIONS = {
  arquearia: {
    id: "arquearia",
    label: "Arquearia",
    group: "Ofensivo à distância",
    summary: "+2 em ataques feitos com armas à distância.",
    description: "+2 nas jogadas de ataque com armas à distância.",
    application: "Automático nos ataques à distância da ficha.",
  },
  defesa: {
    id: "defesa",
    label: "Defesa",
    group: "Defensivo",
    summary: "+1 na CA enquanto estiver usando armadura.",
    description: "+1 na CA enquanto estiver usando armadura.",
    application: "Automático no cálculo de CA quando uma armadura está equipada.",
  },
  duelismo: {
    id: "duelismo",
    label: "Duelismo",
    group: "Ofensivo corpo a corpo",
    summary: "+2 no dano com arma corpo a corpo de uma mão quando não usa outra arma.",
    description: "+2 no dano com arma corpo a corpo empunhada com uma mão e sem outra arma.",
    application: "Registrado no resumo; confirme a condição de mão livre durante o jogo.",
  },
  "armas-grandes": {
    id: "armas-grandes",
    label: "Armas Grandes",
    group: "Ofensivo pesado",
    summary: "Rerrola 1 ou 2 nos dados de dano de armas de duas mãos elegíveis.",
    description: "Quando tirar 1 ou 2 nos dados de dano de armas de duas mãos, pode rerrolar esses dados.",
    application: "Registrado no resumo; a rerrolagem acontece na mesa após a rolagem de dano.",
  },
  protecao: {
    id: "protecao",
    label: "Proteção",
    group: "Defensivo",
    summary: "Com escudo, usa a reação para proteger um aliado adjacente.",
    description: "Com escudo, use sua reação para impor desvantagem ao ataque contra um aliado adjacente.",
    application: "Registrado no resumo; exige escudo e uso da reação.",
  },
  "duas-armas": {
    id: "duas-armas",
    label: "Combate com Duas Armas",
    group: "Ofensivo corpo a corpo",
    summary: "Adiciona o modificador de habilidade ao dano do ataque da mão secundária.",
    description: "Adiciona o modificador de habilidade ao dano do ataque da mão secundária.",
    application: "Registrado no resumo; aplique quando fizer o ataque da mão secundária.",
  },
};
export const LANGUAGE_METADATA = {
  aarakocra: { category: "exotico", spokenBy: "aarakocras", script: "Aarakocra", description: "Idioma agudo e cheio de assobios usado pelos povos alados das montanhas e dos céus." },
  comum: { category: "padrao", spokenBy: "a maioria dos povos civilizados", script: "Comum", description: "O idioma mais difundido para comércio, viagens e convivência entre diferentes culturas." },
  anao: { category: "padrao", spokenBy: "anões", script: "Anão", description: "Língua tradicional dos clãs anões, marcada por termos de linhagem, pedra e metal." },
  aquan: { category: "exotico", spokenBy: "elementais da água e povos marinhos", script: "Aquan", description: "Dialeto elementar fluido, comum entre seres ligados aos mares e às profundezas." },
  auran: { category: "exotico", spokenBy: "elementais do ar e povos dos céus", script: "Auran", description: "Idioma leve e sibilante associado aos ventos, ao voo e aos planos aéreos." },
  elfico: { category: "padrao", spokenBy: "elfos", script: "Élfico", description: "Idioma antigo e melodioso associado à tradição, arte e memória élfica." },
  gith: { category: "exotico", spokenBy: "githyanki e githzerai", script: "Tir'su", description: "Língua marcial e disciplinada dos povos gith espalhados pelos planos." },
  gigante: { category: "padrao", spokenBy: "gigantes e alguns povos das montanhas", script: "Anão", description: "Fala grave e cerimonial, comum entre gigantes e culturas ligadas às alturas." },
  gnomico: { category: "padrao", spokenBy: "gnomos", script: "Anão", description: "Cheio de termos técnicos, humor e curiosidade, muito usado por artesãos e inventores." },
  goblin: { category: "padrao", spokenBy: "goblinoides", script: "Anão", description: "Idioma pragmático e direto, difundido entre goblins, hobgoblins e bugbears." },
  grung: { category: "exotico", spokenBy: "grungs", script: "Grung", description: "Idioma curto e ritmado usado pelos grungs em pântanos e selvas." },
  orc: { category: "padrao", spokenBy: "orcs", script: "Anão", description: "Linguagem dura e marcial, carregada de tradição tribal e força." },
  halfling: { category: "padrao", spokenBy: "halflings", script: "Comum", description: "Fala acolhedora e cotidiana, popular em comunidades pequenas e itinerantes." },
  leonino: { category: "exotico", spokenBy: "leoninos", script: "Leonino", description: "Idioma orgulhoso e sonoro, marcado por tradição oral e honra tribal." },
  loxodonte: { category: "exotico", spokenBy: "loxodontes", script: "Loxodonte", description: "Fala grave e ressonante associada à memória, comunidade e devoção." },
  draconico: { category: "exotico", spokenBy: "dragões, draconatos e arcanistas", script: "Dracônico", description: "Idioma antigo do estudo arcano, respeitado por sua precisão e autoridade." },
  quori: { category: "exotico", spokenBy: "quori e kalashtar ligados a Dal Quor", script: "Quori", description: "Idioma onírico e mental, mais sentido do que pronunciado em conversas comuns." },
  abissal: { category: "exotico", spokenBy: "demônios e cultistas do Abismo", script: "Infernal", description: "Caótico e agressivo, associado a entidades demoníacas e invocações perigosas." },
  celestial: { category: "exotico", spokenBy: "celestiais, clérigos eruditos e servos divinos", script: "Celestial", description: "Idioma solene e luminoso, muito presente em textos sagrados e invocações divinas." },
  falaProfunda: { category: "exotico", spokenBy: "aboleths e cloakers", script: "—", description: "Idioma alienígena e desconcertante, associado a criaturas aberrantes das profundezas." },
  infernal: { category: "exotico", spokenBy: "diabos, tieflings e estudiosos do Baator", script: "Infernal", description: "Formal e preciso, muito usado em contratos, pactos e registros arcanos." },
  silvestre: { category: "exotico", spokenBy: "fadas, criaturas feéricas e espíritos da natureza", script: "Élfico", description: "Língua caprichosa e musical, cheia de metáforas e referências naturais." },
  subcomum: { category: "exotico", spokenBy: "mercadores, espiões e povos do Subterrâneo", script: "Élfico", description: "Idioma de troca e sobrevivência nas profundezas, popular entre drow e forasteiros." },
  primordial: { category: "exotico", spokenBy: "elementais e povos ligados aos planos elementais", script: "Anão", description: "Tronco ancestral dos falares elementais, usado em rituais e pactos primordiais." },
  vedalken: { category: "exotico", spokenBy: "vedalken", script: "Vedalken", description: "Idioma analítico e preciso, ligado a estudo, método e observação constante." },
};
export const DEFAULT_CLASS_FEAT_OPTION_LEVELS = [4, 8, 12, 16, 19];
export const CLASS_FEAT_OPTION_LEVELS = {
  guerreiro: [4, 6, 8, 12, 14, 16, 19],
  ladino: [4, 8, 10, 12, 16, 19],
};

export const SLOT_TABLES = {
  full: [
    [], [2], [3], [4, 2], [4, 3], [4, 3, 2], [4, 3, 3], [4, 3, 3, 1], [4, 3, 3, 2], [4, 3, 3, 3, 1],
    [4, 3, 3, 3, 2], [4, 3, 3, 3, 2, 1], [4, 3, 3, 3, 2, 1], [4, 3, 3, 3, 2, 1, 1], [4, 3, 3, 3, 2, 1, 1],
    [4, 3, 3, 3, 2, 1, 1, 1], [4, 3, 3, 3, 2, 1, 1, 1], [4, 3, 3, 3, 2, 1, 1, 1, 1], [4, 3, 3, 3, 3, 1, 1, 1, 1],
    [4, 3, 3, 3, 3, 2, 1, 1, 1], [4, 3, 3, 3, 3, 2, 2, 1, 1],
  ],
  half: [
    [], [], [2], [3], [3], [4, 2], [4, 2], [4, 3], [4, 3], [4, 3, 2], [4, 3, 2],
    [4, 3, 3], [4, 3, 3], [4, 3, 3, 1], [4, 3, 3, 1], [4, 3, 3, 2], [4, 3, 3, 2], [4, 3, 3, 3, 1],
    [4, 3, 3, 3, 1], [4, 3, 3, 3, 2], [4, 3, 3, 3, 2],
  ],
  artificer: [
    [], [2], [2], [3], [3], [4, 2], [4, 2], [4, 3], [4, 3], [4, 3, 2], [4, 3, 2],
    [4, 3, 3], [4, 3, 3], [4, 3, 3, 1], [4, 3, 3, 1], [4, 3, 3, 2], [4, 3, 3, 2], [4, 3, 3, 3, 1],
    [4, 3, 3, 3, 1], [4, 3, 3, 3, 2], [4, 3, 3, 3, 2],
  ],
  third: [
    [], [], [], [2], [3], [3], [3], [4, 2], [4, 2], [4, 2], [4, 3], [4, 3], [4, 3], [4, 3, 2],
    [4, 3, 2], [4, 3, 2], [4, 3, 3], [4, 3, 3], [4, 3, 3], [4, 3, 3, 1], [4, 3, 3, 1],
  ],
};

export const SPELLCASTING_RULES = {
  artifice: {
    kind: "prepared",
    sourceClassId: "artifice",
    ability: "int",
    multiclassProgression: "half-up",
    slotTable: SLOT_TABLES.artificer,
    cantripsByLevel: [0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4],
    preparedCount: ({ level, mod }) => Math.max(1, Math.ceil(level / 2) + mod),
    selectionLabel: "Magias preparadas",
  },
  bardo: {
    kind: "known",
    sourceClassId: "bardo",
    ability: "car",
    multiclassProgression: "full",
    slotTable: SLOT_TABLES.full,
    cantripsByLevel: [0, 2, 2, 2, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
    spellsKnownByLevel: [0, 4, 5, 6, 7, 8, 9, 10, 11, 12, 14, 15, 15, 16, 18, 19, 19, 20, 22, 22, 22],
    selectionLabel: "Magias conhecidas",
  },
  clerigo: {
    kind: "prepared",
    sourceClassId: "clerigo",
    ability: "sab",
    multiclassProgression: "full",
    slotTable: SLOT_TABLES.full,
    cantripsByLevel: [0, 3, 3, 3, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
    preparedCount: ({ level, mod }) => Math.max(1, level + mod),
    selectionLabel: "Magias preparadas",
  },
  druida: {
    kind: "prepared",
    sourceClassId: "druida",
    ability: "sab",
    multiclassProgression: "full",
    slotTable: SLOT_TABLES.full,
    cantripsByLevel: [0, 2, 2, 2, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
    preparedCount: ({ level, mod }) => Math.max(1, level + mod),
    selectionLabel: "Magias preparadas",
  },
  paladino: {
    kind: "prepared",
    sourceClassId: "paladino",
    ability: "car",
    minLevel: 2,
    multiclassProgression: "half",
    slotTable: SLOT_TABLES.half,
    cantripsByLevel: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    preparedCount: ({ level, mod }) => Math.max(1, Math.floor(level / 2) + mod),
    selectionLabel: "Magias preparadas",
  },
  patrulheiro: {
    kind: "known",
    sourceClassId: "patrulheiro",
    ability: "sab",
    minLevel: 2,
    multiclassProgression: "half",
    slotTable: SLOT_TABLES.half,
    cantripsByLevel: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    spellsKnownByLevel: [0, 0, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7, 8, 8, 9, 9, 10, 10, 11, 11],
    selectionLabel: "Magias conhecidas",
  },
  feiticeiro: {
    kind: "known",
    sourceClassId: "feiticeiro",
    ability: "car",
    multiclassProgression: "full",
    slotTable: SLOT_TABLES.full,
    cantripsByLevel: [0, 4, 4, 4, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
    spellsKnownByLevel: [0, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 12, 13, 13, 14, 14, 15, 15, 15, 15],
    selectionLabel: "Magias conhecidas",
  },
  bruxo: {
    kind: "known",
    sourceClassId: "bruxo",
    ability: "car",
    multiclassProgression: "pact",
    cantripsByLevel: [0, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
    spellsKnownByLevel: [0, 2, 3, 4, 5, 6, 7, 8, 9, 10, 10, 11, 11, 12, 12, 13, 13, 14, 14, 15, 15],
    pactSlotsByLevel: [0, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4],
    pactSlotLevelByLevel: [0, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
    selectionLabel: "Magias conhecidas",
  },
  mago: {
    kind: "prepared",
    sourceClassId: "mago",
    ability: "int",
    multiclassProgression: "full",
    slotTable: SLOT_TABLES.full,
    cantripsByLevel: [0, 3, 3, 3, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
    preparedCount: ({ level, mod }) => Math.max(1, level + mod),
    selectionLabel: "Magias preparadas",
  },
};

export const SUBCLASS_SPELLCASTING_RULES = {
  "guerreiro-cavaleiro-arcano": {
    minLevel: 3,
    kind: "known",
    sourceClassId: "mago",
    ability: "int",
    multiclassProgression: "third",
    restrictedSchools: ["abjuracao", "evocacao"],
    flexibleSpellLevels: [3, 8, 14, 20],
    slotTable: SLOT_TABLES.third,
    cantripsByLevel: [0, 0, 0, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
    spellsKnownByLevel: [0, 0, 0, 3, 4, 4, 4, 5, 6, 7, 8, 8, 9, 10, 10, 11, 11, 11, 12, 13, 13],
    selectionLabel: "Magias conhecidas",
  },
  "ladino-trapaceiro-arcano": {
    minLevel: 3,
    kind: "known",
    sourceClassId: "mago",
    ability: "int",
    multiclassProgression: "third",
    restrictedSchools: ["encantamento", "ilusao"],
    flexibleSpellLevels: [3, 8, 14, 20],
    slotTable: SLOT_TABLES.third,
    cantripsByLevel: [0, 0, 0, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
    spellsKnownByLevel: [0, 0, 0, 3, 4, 4, 4, 5, 6, 7, 8, 8, 9, 10, 10, 11, 11, 11, 12, 13, 13],
    selectionLabel: "Magias conhecidas",
  },
};
export const SPELL_SLOT_LEVELS = [1, 2, 3, 4, 5, 6, 7, 8, 9];
export const XP_BY_LEVEL = [
  0,
  0,
  300,
  900,
  2700,
  6500,
  14000,
  23000,
  34000,
  48000,
  64000,
  85000,
  100000,
  120000,
  140000,
  165000,
  195000,
  225000,
  265000,
  305000,
  355000,
];
export const MULTICLASS_PREREQUISITES = {
  artifice: { mode: "all", checks: [{ attr: "int", min: 13 }] },
  barbaro: { mode: "all", checks: [{ attr: "for", min: 13 }] },
  bardo: { mode: "all", checks: [{ attr: "car", min: 13 }] },
  clerigo: { mode: "all", checks: [{ attr: "sab", min: 13 }] },
  druida: { mode: "all", checks: [{ attr: "sab", min: 13 }] },
  guerreiro: { mode: "any", checks: [{ attr: "for", min: 13 }, { attr: "des", min: 13 }] },
  monge: { mode: "all", checks: [{ attr: "des", min: 13 }, { attr: "sab", min: 13 }] },
  paladino: { mode: "all", checks: [{ attr: "for", min: 13 }, { attr: "car", min: 13 }] },
  patrulheiro: { mode: "all", checks: [{ attr: "des", min: 13 }, { attr: "sab", min: 13 }] },
  ladino: { mode: "all", checks: [{ attr: "des", min: 13 }] },
  feiticeiro: { mode: "all", checks: [{ attr: "car", min: 13 }] },
  bruxo: { mode: "all", checks: [{ attr: "car", min: 13 }] },
  mago: { mode: "all", checks: [{ attr: "int", min: 13 }] },
};
export const MULTICLASS_PROFICIENCIES = {
  artifice: {
    armaduras: ["leve", "media", "escudo"],
    armas: [],
    ferramentas: ["ferramentas-de-ladrao", "ferramentas-de-artesao"],
    textos: ["ferramentas de funileiro"],
  },
  barbaro: {
    armaduras: ["escudo"],
    armas: ["simples", "marcial"],
    ferramentas: [],
    textos: [],
  },
  bardo: {
    armaduras: ["leve"],
    armas: [],
    ferramentas: [],
    textos: ["1 perícia à escolha", "1 instrumento musical à escolha"],
  },
  bruxo: {
    armaduras: ["leve"],
    armas: ["simples"],
    ferramentas: [],
    textos: [],
  },
  clerigo: {
    armaduras: ["leve", "media", "escudo"],
    armas: [],
    ferramentas: [],
    textos: [],
  },
  druida: {
    armaduras: ["leve", "media", "escudo"],
    armas: [],
    ferramentas: [],
    textos: ["druidas evitam armaduras e escudos de metal"],
  },
  feiticeiro: {
    armaduras: [],
    armas: [],
    ferramentas: [],
    textos: [],
  },
  guerreiro: {
    armaduras: ["leve", "media", "escudo"],
    armas: ["simples", "marcial"],
    ferramentas: [],
    textos: [],
  },
  ladino: {
    armaduras: ["leve"],
    armas: [],
    ferramentas: ["ferramentas-de-ladrao"],
    textos: ["1 perícia da classe à escolha"],
  },
  mago: {
    armaduras: [],
    armas: [],
    ferramentas: [],
    textos: [],
  },
  monge: {
    armaduras: [],
    armas: ["simples", "espada-curta"],
    ferramentas: [],
    textos: [],
  },
  paladino: {
    armaduras: ["leve", "media", "escudo"],
    armas: ["simples", "marcial"],
    ferramentas: [],
    textos: [],
  },
  patrulheiro: {
    armaduras: ["leve", "media", "escudo"],
    armas: ["simples", "marcial"],
    ferramentas: [],
    textos: ["1 perícia da classe à escolha"],
  },
};
